### ISSUE TITLE
 { Error: Cannot find module 'angular-cli/plugins/karma'

### ISSUE THREAD

**Issue by ahelord** [primefaces/primeng-quickstart-cli#5]
run this npm run build
npm run test

Error in config file!
 { Error: Cannot find module 'angular-cli/plugins/karma'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/karma.conf.js:12:7)
    at Object.parseConfig (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/node_modules/karma/lib/config.js:342:5)
    at new Server (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/node_modules/karma/lib/server.js:56:20)
    at Promise (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/node_modules/@angular/cli/tasks/test.js:33:33)
    at Class.run (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/node_modules/@angular/cli/tasks/test.js:15:16)
    at Class.run (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/node_modules/@angular/cli/commands/test.js:38:25)
    at Class.<anonymous> (/Users/lrodriguez/Downloads/primeng-quickstart-cli-master/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7) code: 'MODULE_NOT_FOUND' }

**Comment by Nevaan** [comment]
Hi,

I had the same problem and it is related to angular-cli path, which changed. You have to replace 'angular-cli' with '@angular/cli' anywhere it appears in karma.conf.js file. 

Even if you fix this issue, another one appears. I'll report this in separate issue.

**Comment by cagataycivici** [comment]
Fixed now, please try again.
